---
spring:
    web:
      resources:
        static-locations: "file:./app"
cds:
  security:
    mock:
      users:
        - name: manager
          password: manager
          additional:
            email: john.doe@example.com
          roles:
          - manager
        - name: john.doe@example.com
          password: john.doe
          additional:
            email: john.doe@example.com
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

management:
  endpoint:
    health:
      show-components: always
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health"
  health:
    defaults.enabled: false
    ping.enabled: true
    db.enabled: true
    myhealth.enabled: true

---
spring:
  config:
    activate:
      on-profile: default
cds:
  data-source:
    auto-config.enabled: false

---
spring:
  profiles: cloud